export { HeroSection } from './HeroSection'
export { ArchitectureSection } from './ArchitectureSection'
export { BenefitsSection } from './BenefitsSection'
export { WhyStrataSection } from './WhyStrataSection'
export { TeamsSection } from './TeamsSection'
export { CTASection } from './CTASection'
