export { HeroSection } from './HeroSection'
export { ArchitectureSection } from './ArchitectureSection'
export { BenefitsSection } from './BenefitsSection'
export { WhyToposSection } from './WhyToposSection'
export { TeamsSection } from './TeamsSection'
export { CTASection } from './CTASection'
